name: React CI

on:
  push:
    branches: [ "main", "development", "CI"]
    paths:
      - "frontend/**"
      - ".github/workflows/reactTests.yml"
  pull_request:
    branches: [ "main", "development", "CI"]
    paths:
      - "frontend/**"
      - ".github/workflows/reactTests.yml"
  workflow_dispatch: 


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
